// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("CID.Sftp.DirectoryTransfer")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: GuidAttribute("97caff3f-74a3-47fd-b487-9ae103367f1a")]
[assembly: AssemblyProductAttribute("CID.Sftp.DirectoryTransfer")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
        internal const string InformationalVersion = "0.0.1";
    }
}
